package com.emailService.config;

import com.mongodb.MongoClientSettings;
import org.bson.UuidRepresentation;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class MongoDB {

    @Bean
    public com.mongodb.client.MongoClient mongoClient() {
        //.uuidRepresentation(UuidRepresentation.STANDARD) is a configuration option that allows using a UUID as the object id instead of the autogenerated by MongoDB
        return com.mongodb.client.MongoClients.create(MongoClientSettings.builder().uuidRepresentation(UuidRepresentation.STANDARD).build());
    }
}
